[package]
name = "linux-syscalls"
version = "0.1.0"
edition = "2018"
metadata = { msrv = "1.40.0" }

[[example]]
name = 'x86-bare'
required-features = ["bare"]

[features]
default = []
bare = []

[build-dependencies]
cc = "1.0.79"

[dependencies]
linux-sysno = { git = "https://github.com/shurizzle/linux-sysno" }
linux-errno = { git = "https://github.com/shurizzle/linux-errno" }
linux-raw-vdso = { git = "https://github.com/shurizzle/linux-raw-vdso" }
