[package]
name = "linux-syscalls"
version = "0.1.0"
edition = "2018"

[[example]]
name = 'x86-bare'
required-features = ["bare"]

[profile.release]
panic = "abort"
strip = true
opt-level = 3
lto = true
codegen-units = 1

[features]
default = []
bare = []
unchecked_vsyscall = []

[build-dependencies]
cc = "1.0.79"

[dependencies]
linux-sysno = { git = "https://github.com/shurizzle/linux-sysno" }
linux-errno = { git = "https://github.com/shurizzle/linux-errno" }
linux-raw-vdso = { git = "https://github.com/shurizzle/linux-raw-vdso" }
