[target.x86_64-unknown-linux-gnu]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-x86_64:latest"
[target.x86_64-unknown-linux-musl]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-x86_64:latest"

[target.loongarch64-unknown-linux-gnu]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-loongarch64:latest"

[target.i686-unknown-linux-gnu]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-x86:latest"
[target.i686-unknown-linux-musl]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-x86:latest"
[target.i586-unknown-linux-gnu]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-x86:latest"
[target.i586-unknown-linux-musl]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-x86:latest"

[target.aarch64-unknown-linux-gnu]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-aarch64:latest"
[target.aarch64-unknown-linux-musl]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-aarch64:latest"

[target.riscv64gc-unknown-linux-gnu]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-riscv64:latest"
[target.riscv64gc-unknown-linux-musl]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-riscv64:latest"

[target.arm-unknown-linux-gnueabi]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-arm:latest"
[target.armv5te-unknown-linux-gnueabi]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-arm:latest"
[target.armv7-unknown-linux-gnueabi]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-arm:latest"
[target.arm-unknown-linux-gnueabihf]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-arm:latest"
[target.armv7-unknown-linux-gnueabihf]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-arm:latest"
[target.thumbv7neon-unknown-linux-gnueabihf]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-arm:latest"
[target.arm-unknown-linux-musleabi]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-arm:latest"
[target.armv5te-unknown-linux-musleabi]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-arm:latest"
[target.armv7-unknown-linux-musleabi]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-arm:latest"
[target.arm-unknown-linux-musleabihf]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-arm:latest"
[target.armv7-unknown-linux-musleabihf]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-arm:latest"
[target.thumbv7neon-unknown-linux-musleabihf]
xargo = false
build-std = true
image = "shurizzle/toolchain-gnu-musl-cargoenv-arm:latest"

[target.powerpc64-unknown-linux-gnu]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-powerpc64:latest"
[target.powerpc64-unknown-linux-musl]
xargo = false
build-std = true
image = "shurizzle/toolchain-gnu-musl-cargoenv-powerpc64:latest"
[target.powerpc64le-unknown-linux-gnu]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-powerpc64:latest"
[target.powerpc64le-unknown-linux-musl]
xargo = false
build-std = true
image = "shurizzle/toolchain-gnu-musl-cargoenv-powerpc64:latest"

[target.powerpc-unknown-linux-gnu]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-powerpc:latest"
[target.powerpc-unknown-linux-musl]
xargo = false
build-std = true
image = "shurizzle/toolchain-gnu-musl-cargoenv-powerpc:latest"

[target.mips-unknown-linux-gnu]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-mips:latest"
[target.mipsel-unknown-linux-gnu]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-mips:latest"
[target.mips-unknown-linux-musl]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-mips:latest"
[target.mipsel-unknown-linux-musl]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-mips:latest"

[target.mips64-unknown-linux-gnuabi64]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-mips64:latest"
[target.mips64el-unknown-linux-gnuabi64]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-mips64:latest"
[target.mips64-unknown-linux-muslabi64]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-mips64:latest"
[target.mips64el-unknown-linux-muslabi64]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-mips64:latest"

[target.s390x-unknown-linux-gnu]
xargo = false
image = "shurizzle/toolchain-gnu-musl-cargoenv-s390x:latest"
[target.s390x-unknown-linux-musl]
xargo = false
build-std = true
image = "shurizzle/toolchain-gnu-musl-cargoenv-s390x:latest"
